#!/bin/sh

DIR=$PWD

echo "\n~~~~~~~~~~ TESTING ~~~~~~~~~~\n"
cd $DIR/problem1/test && ./tester
cd $DIR/problem2/test && ./tester
cd $DIR/problem3/test && ./tester
cd $DIR/problem4/test && ./tester
cd $DIR/problem5/test && ./tester