#!/bin/sh

DIR=$PWD

echo "~~~~~~~~~~ TESTING ~~~~~~~~~~"
cd $DIR/problem1/test && ./tester
cd $DIR/problem2/test && ./tester
cd $DIR/problem3/test && ./tester
cd $DIR/problem4/test && ./tester
cd $DIR/problem5/test && ./tester
cd $DIR/problem6/test && ./tester
cd $DIR/problem7/test && ./tester
cd $DIR/problem8/test && ./tester
cd $DIR/problem9/test && ./tester
cd $DIR/problem10/test && ./tester
cd $DIR/problem11/test && ./tester