#!/bin/sh

echo "--> prob11"
DIR=test
cd ../ && (cafeobj -no-banner <<EOF
in prob.cafe
quit
EOF
) 2> /dev/null | grep "(true):Bool" > $DIR/prob.out
diff $DIR/prob.expected $DIR/prob.out
rm $DIR/prob.out